version: "3"
networks:
  example_network:
services:
  app1:
    container_name: app1
    image: nginx:1.9
    volumes:
      - ./app1:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - example_network
  app2:
    container_name: app2
    image: nginx:1.9
    volumes:
      - ./app2:/usr/share/nginx/html
    ports:
      - "8081:80"
    networks:
      - example_network
  proxy:
    container_name: proxy
    image: nginx:1.9
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      # - ./proxy/index.html:/usr/share/nginx/html/index.html
      - ./proxy/index.html:/etc/nginx/html/index.html
    ports:
      - "80:80"
    networks:
      - example_network
